from __future__ import annotations

from datetime import UTC, datetime

from git import Repo
from git.exc import InvalidGitRepositoryError, NoSuchPathError

from ..contracts import ToolRequest, ToolResult, ToolStatus
from .base import result_from_data


async def git_diff(request: ToolRequest) -> ToolResult:
    repo = _repo_or_none(request.arguments["root"])
    if repo is None:
        return result_from_data(request, {"skipped": True}, output="not a git repository")
    diff = repo.git.diff()
    return result_from_data(request, {"diff": diff}, output=diff)


async def git_branch(request: ToolRequest) -> ToolResult:
    repo = _repo_or_none(request.arguments["root"])
    if repo is None:
        return result_from_data(request, {"skipped": True}, output="not a git repository")
    return result_from_data(request, {"branch": repo.active_branch.name})


async def git_commit(request: ToolRequest) -> ToolResult:
    if request.dry_run:
        return result_from_data(request, {"dry_run": True}, output="dry-run: commit skipped")
    repo = _repo_or_none(request.arguments["root"])
    if repo is None:
        return result_from_data(request, {"skipped": True}, output="not a git repository")
    message = request.arguments["message"]
    repo.git.add(A=True)
    commit = repo.index.commit(message)
    return result_from_data(request, {"commit": commit.hexsha})


async def rollback_changes(request: ToolRequest) -> ToolResult:
    if request.dry_run:
        return result_from_data(request, {"dry_run": True}, output="dry-run: rollback skipped")
    repo = _repo_or_none(request.arguments["root"])
    if repo is None:
        return result_from_data(request, {"skipped": True}, output="not a git repository")
    paths = request.arguments.get("paths")
    if paths:
        repo.git.checkout("--", *paths)
    else:
        return ToolResult(
            id=request.id,
            task_id=request.task_id,
            name=request.name,
            status=ToolStatus.FAILED,
            output="rollback requires explicit paths",
            completed_at=datetime.now(UTC),
        )
    return result_from_data(request, {"rolled_back": paths})


async def git_snapshot(request: ToolRequest) -> ToolResult:
    repo = _repo_or_none(request.arguments["root"])
    if repo is None:
        return result_from_data(request, {"skipped": True}, output="not a git repository")
    diff = repo.git.diff()
    staged = repo.git.diff("--cached")
    untracked = repo.untracked_files
    data = {
        "branch": repo.active_branch.name if not repo.head.is_detached else "DETACHED",
        "head": repo.head.commit.hexsha,
        "dirty": repo.is_dirty(untracked_files=True),
        "untracked": untracked,
        "diff": diff,
        "staged_diff": staged,
    }
    return result_from_data(request, data, output=f"dirty={data['dirty']} untracked={len(untracked)}")


async def pr_summary(request: ToolRequest) -> ToolResult:
    repo = _repo_or_none(request.arguments["root"])
    if repo is None:
        return result_from_data(request, {"skipped": True}, output="not a git repository")
    diff = repo.git.diff("--stat")
    full_diff = repo.git.diff()
    title = request.arguments.get("title", "Autonomous OctoBot changes")
    summary = [
        f"# {title}",
        "",
        "## Summary",
        "- Generated by OctoBot autonomous coding workflow.",
        "",
        "## Diff Stat",
        "```text",
        diff or "No file changes.",
        "```",
        "",
        "## Risk Notes",
        "- Review generated changes before merge.",
    ]
    return result_from_data(
        request,
        {"summary": "\n".join(summary), "diff_chars": len(full_diff)},
        output="\n".join(summary),
    )


def _repo_or_none(root: str) -> Repo | None:
    try:
        return Repo(root, search_parent_directories=True)
    except (InvalidGitRepositoryError, NoSuchPathError):
        return None
