use serde::Serialize;

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct PlatformCapability {
    pub(crate) id: &'static str,
    pub(crate) name: &'static str,
    pub(crate) architecture: &'static [&'static str],
    pub(crate) modules: &'static [&'static str],
    pub(crate) database_schema: &'static [&'static str],
    pub(crate) agents: &'static [&'static str],
    pub(crate) workflow: &'static [&'static str],
    pub(crate) tui: &'static [&'static str],
    pub(crate) api: &'static [&'static str],
    pub(crate) phases: &'static [&'static str],
    pub(crate) crates: &'static [&'static str],
    pub(crate) commands: &'static [&'static str],
    pub(crate) security: &'static [&'static str],
    pub(crate) scalability: &'static [&'static str],
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub(crate) struct EngineeringOsBlueprint {
    pub(crate) runtime: &'static str,
    pub(crate) event_bus: &'static str,
    pub(crate) persistence: &'static str,
    pub(crate) local_models: &'static str,
    pub(crate) tui: &'static str,
    pub(crate) capabilities: Vec<PlatformCapability>,
}

pub(crate) fn engineering_os_blueprint() -> EngineeringOsBlueprint {
    EngineeringOsBlueprint {
        runtime: "Tokio task supervisor with mpsc/watch event fanout and replayable OpsEvent journal",
        event_bus: "append-only domain events validated by security policy before state reduction",
        persistence: "SQLx/PostgreSQL for durable state, Qdrant-compatible vector memory for semantic recall",
        local_models: "local-first model router with Ollama default and provider adapters for remote escalation",
        tui: "Ratatui control surface with graph, incidents, agents, workflows, security, memory, and console panels",
        capabilities: platform_capabilities(),
    }
}

pub(crate) fn platform_capabilities() -> Vec<PlatformCapability> {
    vec![
        capability(
            "memory-graph",
            "AI Project Memory Graph",
            &[
                "Event-sourced memory writer projects incidents, deployments, fixes, ADRs, workflows, and topology into a typed graph.",
                "Semantic recall combines graph neighborhoods with vector search and project-scoped access control.",
                "Cross-project sharing is explicit through namespace grants and provenance-preserving edges.",
            ],
            &[
                "src/platform/memory_graph.rs",
                "src/persistence/mod.rs",
                "src/models.rs::KnowledgeNode",
                "src/models.rs::KnowledgeEdge",
            ],
            &[
                "memory_nodes(id, project_id, kind, label, summary, confidence, metadata)",
                "memory_edges(id, project_id, from_node, relation, to_node, weight, metadata)",
                "memory_embeddings(node_id, provider, vector_id, dimensions)",
            ],
            &[
                "Memory Agent: compacts events into durable facts",
                "Research Agent: extracts evidence and contradictions",
                "Reviewer Agent: validates provenance before sharing",
            ],
            &[
                "ingest OpsEvent",
                "extract candidate facts",
                "deduplicate by project/kind/label",
                "embed summary",
                "serve recall context",
            ],
            &[
                "Memory graph panel in Infrastructure/Reports",
                "search results from /memory search",
                "edge inspector for incident-to-fix paths",
            ],
            &[
                "GET /api/platform/capabilities",
                "GET /api/memory/search?q=",
                "GET /api/incidents/similar?q=",
            ],
            &[
                "schema",
                "event projector",
                "semantic retrieval",
                "TUI graph navigation",
            ],
            &["sqlx", "serde", "reqwest", "tokio", "ratatui"],
            &[
                "memory search checkout",
                "graph link deploy-1188 fixes inc-042",
            ],
            &[
                "redact secrets before persistence",
                "namespace all project memory",
                "store provenance and confidence on every fact",
            ],
            &[
                "partition by project_id",
                "batch embeddings",
                "cache hot neighborhoods in memory",
            ],
        ),
        capability(
            "coding-workspace",
            "Autonomous Coding Workspace",
            &[
                "Repository indexer builds file, symbol, dependency, and test maps.",
                "Planner decomposes work into bounded patches and validation gates.",
                "Execution agent applies patches only through sandboxed workspace tools.",
            ],
            &[
                "backend/octobot_orchestrator/indexer/repository.py",
                "src/runtime_service.rs",
                "src/workflows/mod.rs",
                "src/platform/coding_workspace.rs",
            ],
            &[
                "repositories(id, root, head_sha, language, metadata)",
                "repo_symbols(repo_id, path, name, kind, span, metadata)",
                "code_tasks(id, repo_id, objective, plan, status)",
                "patch_sets(id, task_id, diff, validation, review)",
            ],
            &[
                "Architect Agent: design constraints and module boundaries",
                "Developer Agent: patch generation",
                "Tester Agent: validation command selection",
                "Reviewer Agent: diff critique and repair loop",
            ],
            &[
                "index",
                "plan",
                "patch",
                "test",
                "review",
                "repair",
                "prepare PR",
            ],
            &[
                "Workspace artifacts table",
                "task DAG view",
                "validation output stream",
            ],
            &[
                "POST /api/tasks",
                "POST /api/tasks/{id}/run",
                "WS /runtime/tools/{tool}",
            ],
            &[
                "index read-only",
                "patch sandbox",
                "validation gates",
                "PR metadata",
            ],
            &[
                "tokio",
                "serde_json",
                "ignore",
                "tree-sitter",
                "git2",
                "similar",
            ],
            &[
                "code plan fix failing test",
                "workspace write operator agent://workspace/note.md note",
            ],
            &[
                "deny path traversal",
                "separate read and write grants",
                "require approval for destructive git operations",
            ],
            &[
                "incremental index by file hash",
                "parallel test shards",
                "bounded repair retries",
            ],
        ),
        capability(
            "software-company",
            "Multi-Agent Software Company",
            &[
                "Role-specific agents communicate over typed IPC messages and shared memory scopes.",
                "Planner creates a DAG, parallel agents execute independent nodes, consensus gates risky decisions.",
            ],
            &["src/agents/mod.rs", "src/workflows/mod.rs", "src/ai/mod.rs"],
            &[
                "agent_processes(pid, agent, role, status, task, memory_scope)",
                "agent_messages(id, sender, recipient, topic, payload)",
                "consensus_votes(id, task_id, agent, decision, rationale)",
            ],
            &["Architect, Developer, Reviewer, Security, Tester, DevOps, Product Manager"],
            &[
                "decompose",
                "assign",
                "parallel execute",
                "vote",
                "merge decision",
                "record rationale",
            ],
            &["Agents process table", "IPC feed", "workflow DAG"],
            &[
                "POST /api/agents/spawn/{role}",
                "GET /api/ipc",
                "GET /api/processes",
            ],
            &["roles", "IPC", "parallel DAG", "consensus policy"],
            &["tokio", "async-channel", "swarms-rs", "rig"],
            &[
                "agent spawn planner",
                "ipc send agent-001 topic payload",
                "ps",
            ],
            &[
                "capability grants per agent",
                "quota enforcement per subject",
                "audit all inter-agent messages",
            ],
            &[
                "work-stealing task queues",
                "agent heartbeats",
                "horizontal runtimes via remote endpoints",
            ],
        ),
        capability(
            "infra-architect",
            "Infrastructure Architect",
            &[
                "Natural-language requirements compile into an intermediate infrastructure plan.",
                "Generators emit Terraform, Kubernetes, Helm, Compose, and CI/CD artifacts with policy validation.",
            ],
            &[
                "src/infra/mod.rs",
                "src/security/mod.rs",
                "src/workflows/mod.rs",
            ],
            &[
                "infra_plans(id, project_id, objective, plan, risk_score)",
                "generated_artifacts(id, plan_id, kind, path, content_hash)",
            ],
            &[
                "Infra Agent",
                "Security Agent",
                "DevOps Agent",
                "Reviewer Agent",
            ],
            &[
                "requirements",
                "plan",
                "generate",
                "validate",
                "deployment plan",
            ],
            &["Infrastructure graph", "artifact preview", "risk report"],
            &["GET /api/state", "GET /api/workspace"],
            &["IR schema", "generators", "validators", "plan simulator"],
            &["serde_yaml", "serde_json", "hcl-rs", "kube", "bollard"],
            &["infra generate k8s api service", "exec kubectl get pods"],
            &[
                "policy-as-code checks",
                "secret redaction",
                "no auto-apply without approval",
            ],
            &[
                "template cache",
                "parallel validators",
                "cluster-scoped rate limits",
            ],
        ),
        capability(
            "predictive-incidents",
            "Predictive Incident Engine",
            &[
                "Observability engine correlates logs, metrics, deployments, and historical incident graph context.",
                "Risk scorer emits early warnings with evidence and forecast horizon.",
            ],
            &[
                "src/observability/mod.rs",
                "src/persistence/mod.rs",
                "src/remediation/mod.rs",
            ],
            &[
                "metric_samples(id, service, cpu, memory, latency, timestamp)",
                "risk_scores(id, service, score, horizon, evidence)",
            ],
            &["Infra Agent", "Memory Agent", "Recovery Agent"],
            &["sample", "correlate", "score", "warn", "propose mitigation"],
            &["Incident list", "health forecast", "timeline panel"],
            &["GET /api/state", "GET /api/incidents/similar?q="],
            &[
                "baseline metrics",
                "correlation",
                "forecasting",
                "policy-linked warnings",
            ],
            &["tokio", "serde", "statrs", "sqlx"],
            &["investigate nginx_latency", "analyze-logs auth-service"],
            &[
                "explain every score",
                "avoid autonomous write actions",
                "bound data retention",
            ],
            &[
                "rolling windows",
                "service partitioning",
                "downsample cold metrics",
            ],
        ),
        capability(
            "self-healing",
            "Self-Healing Infrastructure",
            &[
                "Recovery engine maps incidents to approved remediation policies and dry-run commands.",
                "Actions progress through proposal, approval, execution, verification, and replay recording.",
            ],
            &[
                "src/remediation/mod.rs",
                "src/runtime/mod.rs",
                "src/security/mod.rs",
            ],
            &[
                "remediation_policies(id, selector, action, risk, approvals)",
                "recovery_runs(id, policy_id, target, status, evidence)",
            ],
            &["Recovery Agent", "Security Agent", "DevOps Agent"],
            &[
                "detect",
                "propose",
                "approve",
                "execute dry-run",
                "verify",
                "rollback",
            ],
            &[
                "Recovery action queue",
                "approval controls",
                "replay timeline",
            ],
            &["GET /api/state", "POST /api/processes/{agent}/pause"],
            &[
                "read-only repairs",
                "approval gates",
                "write actions",
                "closed-loop verification",
            ],
            &["tokio", "crossterm", "serde_json"],
            &["recover edge-nginx", "approve rec-0001"],
            &["role-based approvals", "dry-run default", "kill switch"],
            &[
                "idempotent actions",
                "deduped incidents",
                "per-cluster concurrency limits",
            ],
        ),
        capability(
            "security-ops",
            "AI Security Operations Center",
            &[
                "Security tooling scans dependencies, source, logs, plugins, containers, and sandbox drift.",
                "Findings become explainability records, threat signals, and posture reports.",
            ],
            &[
                "src/security/mod.rs",
                "src/plugins/mod.rs",
                "src/reports.rs",
            ],
            &[
                "security_findings(id, source, severity, title, evidence, status)",
                "security_reports(id, scope, summary, document)",
            ],
            &["Security Agent", "Reviewer Agent", "DevOps Agent"],
            &[
                "scan",
                "triage",
                "prioritize",
                "report",
                "open remediation task",
            ],
            &["Security summary", "findings table", "policy panel"],
            &["GET /api/policy", "GET /api/syscalls", "GET /api/plugins"],
            &[
                "offline scanners",
                "container scan",
                "threat intel",
                "automated reports",
            ],
            &["serde", "sha2", "regex", "reqwest"],
            &["policy show", "syscalls", "plugin disable workflow-rca"],
            &[
                "signed plugins",
                "secret detection",
                "egress controls for threat feeds",
            ],
            &["incremental scans", "finding dedupe", "severity queues"],
        ),
        capability(
            "research-swarm",
            "Research Swarm",
            &[
                "Research agents collect docs, repositories, benchmarks, and trend data into sourced reports.",
                "Contradiction tracking and memory extraction preserve reusable knowledge.",
            ],
            &["src/ai/mod.rs", "src/agents/mod.rs", "src/reports.rs"],
            &[
                "research_runs(id, topic, status, confidence)",
                "research_sources(id, run_id, uri, reliability, evidence)",
            ],
            &["Research Agent", "Reviewer Agent", "Memory Agent"],
            &[
                "scope",
                "collect",
                "compare",
                "rank",
                "report",
                "store knowledge",
            ],
            &["Research profile", "reports list", "memory links"],
            &["GET /api/state"],
            &[
                "docs ingestion",
                "repo analysis",
                "benchmarks",
                "trend reports",
            ],
            &["reqwest", "serde_json", "tokio", "rig"],
            &["research confidence", "generate-report incident_042"],
            &[
                "source attribution",
                "rate limits",
                "untrusted content isolation",
            ],
            &[
                "parallel source fetch",
                "cache fetched docs",
                "dedupe evidence",
            ],
        ),
        capability(
            "model-router",
            "Smart Model Router",
            &[
                "Router selects provider/model by workload, health, latency, quality, cost, and local availability.",
                "Ollama is preferred for local-first operation; remote providers require explicit login/config.",
            ],
            &["src/ai/mod.rs", "backend/octobot_orchestrator/providers.py"],
            &[
                "model_providers(id, kind, endpoint, health, cost_hint)",
                "model_routing_events(id, task_id, model, latency_ms, quality_score)",
            ],
            &["Planner Agent", "Execution Agent", "Validation Agent"],
            &[
                "classify workload",
                "rank models",
                "execute",
                "record quality",
                "adapt",
            ],
            &["Model health list", "token usage", "provider login"],
            &["GET /api/state", "POST login command through TUI"],
            &[
                "static router",
                "health probes",
                "quality scoring",
                "budget-aware routing",
            ],
            &["ollama-rs", "rig", "reqwest", "serde"],
            &[
                "login ollama http://localhost:11434",
                "chat summarize the current system state",
            ],
            &["redact API keys", "provider allowlist", "local default"],
            &["provider pools", "circuit breakers", "latency histograms"],
        ),
        capability(
            "plugin-marketplace",
            "Plugin Marketplace",
            &[
                "Registry manages signed plugin manifests, versions, permissions, sandbox policy, and hot status changes.",
                "Plugin host executes tools through explicit capability boundaries.",
            ],
            &[
                "src/plugins/registry.rs",
                "src/plugins/host.rs",
                "src/security/mod.rs",
            ],
            &[
                "plugin_registry(name, version, manifest, signature, status)",
                "plugin_permissions(plugin, capability, granted_by)",
            ],
            &["Security Agent", "Reviewer Agent", "Plugin Agent"],
            &[
                "import",
                "verify",
                "grant permissions",
                "enable",
                "hot reload",
                "audit",
            ],
            &["Marketplace package list", "plugin status panel"],
            &["GET /api/plugins", "GET /api/packages"],
            &[
                "local registry",
                "version locks",
                "sandbox",
                "community feeds",
            ],
            &["serde_json", "libloading", "sha2", "tokio"],
            &[
                "marketplace import local-tool",
                "plugin enable local-research",
            ],
            &["manifest signatures", "least privilege", "sandboxed IO"],
            &[
                "registry index cache",
                "lazy load plugins",
                "versioned capability checks",
            ],
        ),
        capability(
            "live-infra-map",
            "Live Infrastructure Map",
            &[
                "Infra integrations discover nodes and dependency edges on an interval.",
                "Topology graph renders health, relations, and navigation targets in the TUI.",
            ],
            &[
                "src/infra/mod.rs",
                "src/models.rs::TopologySnapshot",
                "src/ui.rs",
            ],
            &[
                "infra_nodes(id, cluster, kind, health, metrics)",
                "topology_edges(source, target, relation, updated_at)",
            ],
            &["Infra Agent", "DevOps Agent", "Recovery Agent"],
            &[
                "discover",
                "build topology",
                "correlate health",
                "render graph",
                "navigate",
            ],
            &["Infrastructure panel", "compact dashboard", "graph links"],
            &["GET /api/state"],
            &[
                "discovery",
                "health overlays",
                "interactive navigation",
                "cluster filters",
            ],
            &["ratatui", "tokio", "serde", "kube"],
            &["exec docker ps", "exec kubectl get pods"],
            &[
                "read-only integrations",
                "credential isolation",
                "redacted labels",
            ],
            &[
                "delta updates",
                "cluster partitioning",
                "bounded edge retention",
            ],
        ),
        capability(
            "cost-optimizer",
            "Cost Optimization Engine",
            &[
                "Usage analyzer combines resource metrics, cloud inventory, and historical demand.",
                "Recommendation engine scores waste, rightsizing, capacity, and forecast confidence.",
            ],
            &[
                "src/infra/mod.rs",
                "src/observability/mod.rs",
                "src/reports.rs",
            ],
            &[
                "cost_samples(id, provider, service, amount, period)",
                "cost_recommendations(id, target, savings, risk, action)",
            ],
            &["Infra Agent", "Product Manager Agent", "DevOps Agent"],
            &[
                "collect",
                "normalize",
                "detect waste",
                "forecast",
                "recommend",
            ],
            &["Cost panel in Reports/Infrastructure", "forecast gauge"],
            &["GET /api/state"],
            &[
                "utilization",
                "cloud cost adapters",
                "recommendations",
                "capacity plans",
            ],
            &["rust_decimal", "chrono", "serde", "sqlx"],
            &["cost analyze cluster", "generate-report cost"],
            &[
                "read-only billing access",
                "no autonomous downsizing",
                "approval for changes",
            ],
            &[
                "provider-specific collectors",
                "daily rollups",
                "forecast caches",
            ],
        ),
        capability(
            "incident-replay",
            "Incident Replay Studio",
            &[
                "Replay uses the append-only event log to reconstruct incident timelines and recovery branches.",
                "Training mode replays evidence, decisions, and outcomes without executing actions.",
            ],
            &[
                "src/persistence/mod.rs",
                "src/models.rs::ReplayCursor",
                "src/ui.rs",
            ],
            &[
                "replay_sessions(id, incident_id, cursor, mode)",
                "replay_annotations(id, session_id, event_id, note)",
            ],
            &["Reviewer Agent", "Recovery Agent", "Product Manager Agent"],
            &[
                "load events",
                "reconstruct state",
                "step timeline",
                "compare recovery",
                "extract lesson",
            ],
            &["Replay controls", "timeline", "root-cause graph"],
            &["GET /api/replay/events", "GET /api/replay/reconstruct"],
            &[
                "event replay",
                "timeline UI",
                "branch comparison",
                "training mode",
            ],
            &["sqlx", "serde_json", "ratatui"],
            &["replay start", "replay step"],
            &[
                "disable side effects",
                "redact historical secrets",
                "signed audit records",
            ],
            &[
                "stream events by incident",
                "snapshot checkpoints",
                "cold archive",
            ],
        ),
        capability(
            "pair-programmer",
            "AI Pair Programmer",
            &[
                "Interactive assistant uses current repo index, memory graph, selected files, and terminal validation output.",
                "Suggestions are patch-first, test-aware, and reviewed before write operations.",
            ],
            &["src/ai/mod.rs", "src/runtime_service.rs", "src/ui.rs"],
            &[
                "pair_sessions(id, repo_id, objective, context)",
                "pair_suggestions(id, session_id, diff, rationale, status)",
            ],
            &["Developer Agent", "Reviewer Agent", "Tester Agent"],
            &[
                "chat",
                "retrieve context",
                "suggest patch",
                "generate tests",
                "validate",
            ],
            &["Chat panel", "workspace artifacts", "validation output"],
            &["GET /api/conversation", "GET /api/workspace"],
            &[
                "context chat",
                "test generation",
                "debugging",
                "refactoring",
            ],
            &["rig", "ollama-rs", "similar", "tokio"],
            &[
                "chat summarize the current system state",
                "assign agent-001 refactor api",
            ],
            &[
                "no silent writes",
                "path allowlist",
                "prompt-injection scanning",
            ],
            &[
                "context compression",
                "file-level caches",
                "streaming responses",
            ],
        ),
        capability(
            "engineering-os",
            "AI-Native Engineering Operating System",
            &[
                "Unifies software engineering, infrastructure, security, research, remediation, orchestration, memory, and workflow automation.",
                "All subsystems speak OpsEvent and expose local-first terminal-native control.",
            ],
            &[
                "src/main.rs",
                "src/runtime/mod.rs",
                "src/api.rs",
                "src/ui.rs",
            ],
            &[
                "ops_events(id, event_type, event, state)",
                "system_services(name, status, health, notes)",
                "resource_quotas(subject, limits, usage)",
            ],
            &["All role agents coordinated by planner and policy"],
            &[
                "observe",
                "reason",
                "act with policy",
                "persist",
                "replay",
                "learn",
            ],
            &[
                "Dashboard",
                "Agents",
                "Infrastructure",
                "Workflows",
                "Reports",
                "Settings",
                "Chat",
            ],
            &[
                "GET /health",
                "GET /api/state",
                "GET /api/platform/capabilities",
            ],
            &[
                "core contracts",
                "capability modules",
                "distributed runtimes",
                "operator hardening",
            ],
            &["tokio", "ratatui", "serde", "sqlx", "tracing", "axum"],
            &["boot status", "services", "tasks-report"],
            &[
                "policy-first event bus",
                "auditability",
                "least privilege",
                "local-first by default",
            ],
            &[
                "horizontal agent runtimes",
                "append-only logs",
                "stateless API replicas",
            ],
        ),
    ]
}

fn capability(
    id: &'static str,
    name: &'static str,
    architecture: &'static [&'static str],
    modules: &'static [&'static str],
    database_schema: &'static [&'static str],
    agents: &'static [&'static str],
    workflow: &'static [&'static str],
    tui: &'static [&'static str],
    api: &'static [&'static str],
    phases: &'static [&'static str],
    crates: &'static [&'static str],
    commands: &'static [&'static str],
    security: &'static [&'static str],
    scalability: &'static [&'static str],
) -> PlatformCapability {
    PlatformCapability {
        id,
        name,
        architecture,
        modules,
        database_schema,
        agents,
        workflow,
        tui,
        api,
        phases,
        crates,
        commands,
        security,
        scalability,
    }
}
